[SERVICE]
    flush        1
    daemon       Off
    log_level    info
    parsers_file parsers.conf

[INPUT]
    name              tail
    path              /var/lib/docker/containers/*/*.log
    parser            docker
    tag               docker.*
    refresh_interval  5
    mem_buf_limit     5MB
    skip_long_lines   On

[FILTER]
    name              modify
    match             docker.*
    add               cluster skdy-ticket
    add               env production

[FILTER]
    name              nest
    match             docker.*
    operation         lift
    nested_under      attrs
    add_prefix        attr.

[FILTER]
    name              modify
    match             docker.*
    rename            attr.com.docker.compose.service service
    rename            attr.com.docker.compose.project project

[OUTPUT]
    name              loki
    match             docker.*
    host              loki
    port              3100
    labels            cluster=skdy-ticket,env=production
    label_keys        service,project
    drop_records_with_empty_line On
