[SERVICE]
    flush        1
    daemon       Off
    log_level    info
    parsers_file parsers.conf

[INPUT]
    name              tail
    path              /var/lib/docker/containers/*/*.log
    parser            docker
    tag               docker.*
    refresh_interval  5
    mem_buf_limit     50MB
    skip_long_lines   On
    db                /fluent-bit/state/fluentbit.db
    db.sync           normal

[FILTER]
    name              modify
    match             docker.*
    add               cluster skdy-ticket
    add               env production

[FILTER]
    name              nest
    match             docker.*
    operation         lift
    nested_under      attrs
    add_prefix        attr.

[FILTER]
    name              modify
    match             docker.*
    rename            attr.com.docker.compose.service service
    rename            attr.com.docker.compose.project project

[OUTPUT]
    Name        loki
    Match       docker.*
    Host        loki
    Port        3100
    Uri         /loki/api/v1/push
    Labels      cluster=skdy-ticket,env=production
    Label_keys  $service,$project

